
import java.awt.Graphics;
import java.io.File;
import smm.moh.video.VideoListener;
import uk.co.caprica.vlcj.component.EmbeddedMediaPlayerComponent;
import uk.co.caprica.vlcj.player.MediaPlayerEventListener;
import uk.co.caprica.vlcj.player.embedded.EmbeddedMediaPlayer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author eyehalcon97
 */
public class VentanaVideo extends VentanaInterna {

    /**
     * Creates new form VentanaVideo
     * 
     */

    
    private EmbeddedMediaPlayer video=null;
    private File fMedia;
    private javax.swing.JButton botonStop;
    private javax.swing.JButton botonPlay;
    public VentanaVideo() {
        super();
        initComponents();
    }

    public VentanaVideo(File f,javax.swing.JButton botonStop,javax.swing.JButton botonPlay) {
        super();
        this.botonPlay=botonPlay;
        this.botonStop=botonStop;
        initComponents();
        fMedia = f;   
        EmbeddedMediaPlayerComponent aVisual = new EmbeddedMediaPlayerComponent();    
        jPanel1.add(aVisual,java.awt.BorderLayout.CENTER);    

        video = aVisual.getMediaPlayer();
        video.addMediaPlayerEventListener(new VideoListener(botonStop,botonPlay));
        
        
    }

    public void play() {   
        if (video != null) {     
            if(video.isPlayable()){       //Si se estaba reproduciendo       
                video.play();     
            } else {
                
                video.playMedia(fMedia.getAbsolutePath());     
            }   
        }         
    } 
 
    public void stop() {   
        if (video != null) {     
            if (video.isPlaying()) {       
                video.pause();     
            } else {       
                video.stop();     
            }   
        }         
    } 
    public void addMediaPlayerEventListener(MediaPlayerEventListener ml) {  
        if (video != null) {     
            video.addMediaPlayerEventListener(ml);   
        } 
    } 
    public void paintComponent(Graphics g){
        super.paintComponent(g);
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();

        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 390, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 268, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
        // TODO add your handling code here:
        stop();
    }//GEN-LAST:event_formInternalFrameClosing

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        // TODO add your handling code here:
        repaint();
    }//GEN-LAST:event_formInternalFrameActivated


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
