
import java.awt.Color;
import java.io.File;
import javax.swing.Icon;
import javax.swing.JFileChooser;





/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author eyehalcon97
 */
public class frame extends javax.swing.JFrame {

    /**
     * Creates new form frame
     */
    boolean barraestado=true;
    Color color = new Color(0,0,0);
    Formas forma;
    public frame() {
        initComponents();
        this.setSize(800, 600);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jDialog1 = new javax.swing.JDialog();
        menu = new javax.swing.ButtonGroup();
        colores = new javax.swing.ButtonGroup();
        pie = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        negro = new javax.swing.JButton();
        rojo = new javax.swing.JButton();
        azul = new javax.swing.JButton();
        blanco = new javax.swing.JButton();
        amarillo = new javax.swing.JButton();
        verde = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jPanel5 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        selectedcolor = new javax.swing.JButton();
        estado = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        head = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        lapiz = new javax.swing.JToggleButton();
        linea = new javax.swing.JToggleButton();
        rectangulo = new javax.swing.JToggleButton();
        elipse = new javax.swing.JToggleButton();
        lienzo1 = new Lienzo();
        jMenuBar1 = new javax.swing.JMenuBar();
        File = new javax.swing.JMenu();
        FileNuevo = new javax.swing.JMenuItem();
        FileAbrir = new javax.swing.JMenuItem();
        FileGuardar = new javax.swing.JMenuItem();
        Edicion = new javax.swing.JMenu();
        EdicionVerbarra = new javax.swing.JCheckBoxMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pie.setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setMaximumSize(new java.awt.Dimension(10, 10));
        jPanel2.setPreferredSize(new java.awt.Dimension(80, 80));
        jPanel2.setLayout(new java.awt.GridLayout(2, 3));

        negro.setBackground(new java.awt.Color(0, 0, 0));
        colores.add(negro);
        negro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colo(evt);
            }
        });
        jPanel2.add(negro);

        rojo.setBackground(new java.awt.Color(204, 0, 0));
        colores.add(rojo);
        rojo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colo(evt);
            }
        });
        jPanel2.add(rojo);

        azul.setBackground(new java.awt.Color(0, 51, 255));
        colores.add(azul);
        azul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colo(evt);
            }
        });
        jPanel2.add(azul);

        blanco.setBackground(new java.awt.Color(255, 255, 255));
        colores.add(blanco);
        blanco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colo(evt);
            }
        });
        jPanel2.add(blanco);

        amarillo.setBackground(new java.awt.Color(255, 255, 0));
        colores.add(amarillo);
        amarillo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colo(evt);
            }
        });
        jPanel2.add(amarillo);

        verde.setBackground(new java.awt.Color(0, 153, 0));
        colores.add(verde);
        verde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colo(evt);
            }
        });
        jPanel2.add(verde);

        jPanel1.add(jPanel2, java.awt.BorderLayout.LINE_START);

        jCheckBox1.setText("Relleno");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox1, java.awt.BorderLayout.LINE_END);

        jPanel5.setLayout(new java.awt.BorderLayout());

        jPanel3.setLayout(new java.awt.BorderLayout());

        jLabel1.setText("Color Seleccionado");
        jPanel3.add(jLabel1, java.awt.BorderLayout.PAGE_END);

        selectedcolor.setBackground(new java.awt.Color(0, 0, 0));
        selectedcolor.setEnabled(false);
        jPanel3.add(selectedcolor, java.awt.BorderLayout.CENTER);

        jPanel5.add(jPanel3, java.awt.BorderLayout.LINE_START);

        jPanel1.add(jPanel5, java.awt.BorderLayout.CENTER);

        pie.add(jPanel1, java.awt.BorderLayout.PAGE_START);

        estado.setText("Paint");
        pie.add(estado, java.awt.BorderLayout.PAGE_END);
        pie.add(jSeparator1, java.awt.BorderLayout.CENTER);

        getContentPane().add(pie, java.awt.BorderLayout.PAGE_END);

        head.setLayout(new java.awt.BorderLayout());

        jPanel8.setLayout(new java.awt.GridLayout(1, 0));

        lapiz.setName("Lapiz");
        menu.add(lapiz);
        lapiz.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Lapiz.gif"))); // NOI18N
        lapiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                herramienta(evt);
            }
        });
        jPanel8.add(lapiz);

        linea.setName("Linea");
        menu.add(linea);
        linea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Linea.gif"))); // NOI18N
        linea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                herramienta(evt);
            }
        });
        jPanel8.add(linea);

        rectangulo.setName("Rectangulo");
        menu.add(rectangulo);
        rectangulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Rectangulo.gif"))); // NOI18N
        rectangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                herramienta(evt);
            }
        });
        jPanel8.add(rectangulo);

        elipse.setName("Elipse");
        menu.add(elipse);
        elipse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ovalo.gif"))); // NOI18N
        elipse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                herramienta(evt);
            }
        });
        jPanel8.add(elipse);

        head.add(jPanel8, java.awt.BorderLayout.LINE_START);

        getContentPane().add(head, java.awt.BorderLayout.PAGE_START);

        javax.swing.GroupLayout lienzo1Layout = new javax.swing.GroupLayout(lienzo1);
        lienzo1.setLayout(lienzo1Layout);
        lienzo1Layout.setHorizontalGroup(
            lienzo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 589, Short.MAX_VALUE)
        );
        lienzo1Layout.setVerticalGroup(
            lienzo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(lienzo1, java.awt.BorderLayout.CENTER);

        File.setText("Archivo");
        File.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                FileMouseEntered(evt);
            }
        });
        File.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FileActionPerformed(evt);
            }
        });

        FileNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/NuevoBoceto.GIF"))); // NOI18N
        FileNuevo.setText("Nuevo");
        menu.add(FileNuevo);
        FileNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FileNuevoActionPerformed(evt);
            }
        });
        File.add(FileNuevo);

        FileAbrir.setText("Abrir");
        FileAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FileAbrirActionPerformed(evt);
            }
        });
        File.add(FileAbrir);

        FileGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Guardar.gif"))); // NOI18N
        FileGuardar.setText("Guardar");
        FileGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FileGuardarActionPerformed(evt);
            }
        });
        File.add(FileGuardar);

        jMenuBar1.add(File);

        Edicion.setText("Edición");

        EdicionVerbarra.setSelected(true);
        EdicionVerbarra.setText("Ver barra de estado");
        EdicionVerbarra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EdicionVerbarraActionPerformed(evt);
            }
        });
        Edicion.add(EdicionVerbarra);

        jMenuBar1.add(Edicion);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FileMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FileMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_FileMouseEntered

    private void FileGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FileGuardarActionPerformed
        // TODO add your handling code here:
        JFileChooser dlg = new JFileChooser();
        int resp = dlg.showSaveDialog(this);
        if( resp == JFileChooser.APPROVE_OPTION) {
        File f = dlg.getSelectedFile();
        }
    }//GEN-LAST:event_FileGuardarActionPerformed

    private void FileAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FileAbrirActionPerformed
        // TODO add your handling code here:
        JFileChooser dlg = new JFileChooser();
        int resp = dlg.showOpenDialog(this);
        if( resp == JFileChooser.APPROVE_OPTION) {
        File f = dlg.getSelectedFile();
        }
    }//GEN-LAST:event_FileAbrirActionPerformed

    private void FileNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FileNuevoActionPerformed
        // TODO add your handling code here:
         estado.setText("Paint");
        forma = null;
        color = new Color(0,0,0);
        selectedcolor.setBackground(color);
        lienzo1.setColor(color);
        lienzo1.setFormas(forma);
        menu.clearSelection();
        System.out.print("");
    }//GEN-LAST:event_FileNuevoActionPerformed

    private void EdicionVerbarraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EdicionVerbarraActionPerformed
        // TODO add your handling code here:
        barraestado = !barraestado;
        if(barraestado == false){
            estado.setText("");
        }else{
        estado.setText("Paint");
        }
    }//GEN-LAST:event_EdicionVerbarraActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
        lienzo1.setRelleno();
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void colo(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colo
        // TODO add your handling code here:
        javax.swing.JButton boton;
        boton = (javax.swing.JButton) evt.getSource();

        color = boton.getBackground();
        selectedcolor.setBackground(color);
        lienzo1.setColor(color);
    }//GEN-LAST:event_colo

    private void herramienta(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_herramienta
        // TODO add your handling code here:
        javax.swing.JToggleButton boton;
        boton = (javax.swing.JToggleButton) evt.getSource();
        if(boton.getName() == "Lapiz"){
            forma=Formas.PUNTO;
            
        }else
            if(boton.getName() == "Linea"){
                forma = Formas.LINEA;
            }else
                if(boton.getName() == "Rectangulo"){
                    forma = Formas.RECTANGULO;
                }else
                    if(boton.getName() == "Elipse"){
                        forma = Formas.ELIPSE;
                    }
        estado.setText(forma.toString());
        lienzo1.setFormas(forma);
    }//GEN-LAST:event_herramienta

    private void FileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FileActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_FileActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Edicion;
    private javax.swing.JCheckBoxMenuItem EdicionVerbarra;
    private javax.swing.JMenu File;
    private javax.swing.JMenuItem FileAbrir;
    private javax.swing.JMenuItem FileGuardar;
    private javax.swing.JMenuItem FileNuevo;
    private javax.swing.JButton amarillo;
    private javax.swing.JButton azul;
    private javax.swing.JButton blanco;
    private javax.swing.ButtonGroup colores;
    private javax.swing.JToggleButton elipse;
    private javax.swing.JLabel estado;
    private javax.swing.JPanel head;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JToggleButton lapiz;
    private Lienzo lienzo1;
    private javax.swing.JToggleButton linea;
    private javax.swing.ButtonGroup menu;
    private javax.swing.JButton negro;
    private javax.swing.JPanel pie;
    private javax.swing.JToggleButton rectangulo;
    private javax.swing.JButton rojo;
    private javax.swing.JButton selectedcolor;
    private javax.swing.JButton verde;
    // End of variables declaration//GEN-END:variables
}
