/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package smm.moh.graficos;

import smm.moh.iu.Formas;
import java.awt.Graphics;
import java.awt.Color;
import java.awt.Graphics2D;
import java.awt.Shape;
import java.awt.geom.Line2D;
import java.awt.geom.Point2D;
import java.awt.geom.Rectangle2D;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.List;
/**
/**
 *
 * @author eyehalcon97
 */
public class Lienzo2D extends javax.swing.JPanel {

    /**
     * Creates new form Lienzo2D
     */
    
    private Point2D pin = new Point2D.Double(-10, -10);
    private Point2D pout = new Point2D.Double(-10, -10);
    private Color color;
    private Formas forma;
    private boolean relleno = false;
    List<Shape> vShape = new ArrayList();
    
    public Lienzo2D() {
        initComponents();
    }
    
    public void paint(Graphics g){
        super.paint(g);
    Graphics2D g2d=(Graphics2D)g;
    double x, y;
        double w, h;
    if(null != forma)switch (forma) {
            case PUNTO:
                Line2D punto = new Line2D.Double(pin, pin);
                vShape.add(punto);
                break;
            case LINEA:
                Line2D linea = new Line2D.Double(pin, pout);
                vShape.add(linea);
                break;
            case RECTANGULO:
                if(pin.getX() > pout.getX()){
                x = pout.getX();
                w = pin.getX() - pout.getX();
                }else{
                    x = pin.getX();
                    w = pout.getX() - pin.getX();
                }
             
                if(pin.getY() > pout.getY()){
                    y = pout.getY();
                    h = pin.getY() - pout.getY();
                    }else{
                        y = pin.getY();
                    h = pout.getY() - pin.getY();
                }
                if(relleno == false){
                    Rectangle2D rectangulo = new Rectangle2D.Double(x, y, w, h);
                    vShape.add(rectangulo);
                }
                
                break;
                /*
            case ELIPSE:
                if(pin.x > pout.x){
                x = pout.x;
                w = pin.x - pout.x;
                }else{
                    x = pin.x;
                    w = pout.x - pin.x;
                }
             
                if(pin.y > pout.y){
                    y = pout.y;
                    h = pin.y - pout.y;
                    }else{
                        y = pin.y;
                    h = pout.y - pin.y;
                }
                if(relleno == false){
                    g.drawOval(x, y, w, h);
                }else{
                    g.fillOval(x, y, w, h);
                }
                
                
                break;
            default:
                break;
                */
        }
    
    
    System.out.print(vShape.toString());
        for(Shape s:vShape){
            g2d.draw(s);
        }
        
    }
    public void setColor(Color color){
        this.color = new Color(color.getRGB());
    }
    public void setFormas(Formas forma){
        this.forma=forma;
    }
    public void setRelleno(){
        relleno = !relleno;
    }
    
    private void formMouseClicked(java.awt.event.MouseEvent evt) {
         pin=new Point2D.Float(evt.getX(),evt.getY());
            
            repaint();
        // TODO add your handling code here:
    }                                 

    private void formMouseDragged(java.awt.event.MouseEvent evt) {                                  
        // TODO add your handling code here:
            
             //pout=new Point2D.Float(evt.getX(),evt.getY());
            
            //repaint();
        
       
       
               
        
    }                                 

    private void formMousePressed(java.awt.event.MouseEvent evt) {                                  
        // TODO add your handling code here:
         pin=new Point2D.Float(evt.getX(),evt.getY());
        repaint();
    }      

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
