


import smm.moh.iu.Formas;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Point;
import java.awt.Transparency;
import java.awt.color.ColorSpace;
import java.awt.geom.AffineTransform;
import java.awt.geom.Point2D;
import java.awt.image.AffineTransformOp;
import java.awt.image.BufferedImage;
import java.awt.image.ByteLookupTable;
import java.awt.image.ColorConvertOp;
import java.awt.image.ComponentColorModel;
import java.awt.image.ConvolveOp;
import java.awt.image.DataBuffer;
import java.awt.image.Kernel;
import java.awt.image.LookupOp;
import java.awt.image.RescaleOp;
import java.awt.image.WritableRaster;
import java.io.File;
import javax.imageio.ImageIO;
import javax.swing.JFileChooser;
import sm.image.KernelProducer;
import sm.image.LookupTableProducer;
import java.awt.image.LookupTable;
import java.util.List;
import sm.image.EqualizationOp;
import sm.image.TintOp;
import sm.sound.SMClipPlayer;
import sm.sound.SMPlayer;
import sm.sound.SMRecorder;
import sm.sound.SMSoundRecorder;
import smm.moh.graficos.MiFigura;
import smm.moh.graficos.MiRectangularShape;
import smm.moh.audio.ManejadorAudio;
import smm.moh.imagen.NegativoOp;
import smm.moh.imagen.RandomOp;
import smm.moh.imagen.SepiaOp;
import smm.moh.imagen.UmbralizacionOp;









/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author eyehalcon97
 * Mi clase VentanaPrincipal
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    int grados =0;
    private boolean barraestado=true;
    private boolean barraformas=true;
    private boolean barraatributos=true;
    private boolean barraimagen=true;
    private boolean formas=false;
    Formas form = null;
    Color color = new Color(0,0,0);
    Formas forma=null;
    BufferedImage imgSource=null;
    Color colors[] = { Color.RED, Color.BLUE,Color.BLACK,Color.WHITE };

    int cordenadaX = 0;
    int cordenadaY = 0;
    private SMPlayer player = null; 
    private SMRecorder recorder=null;
    private File rec=new File("Bufer");
    private List<MiFigura> lista;
    private MiLista list_model = new MiLista();
    /**
    *
    * Constructor por defecto
    * 
    */
    public VentanaPrincipal() {
        initComponents();
        this.setSize(800, 600);
        botonstop.setEnabled(false);
        li.setModel(list_model);
        jPanel17.setVisible(false);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jDialog1 = new javax.swing.JDialog();
        menu = new javax.swing.ButtonGroup();
        jPanel7 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        list = new javax.swing.JMenu();
        pie = new javax.swing.JPanel();
        estado = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jSeparator3 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSlider1 = new javax.swing.JSlider();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Filtro = new javax.swing.JComboBox<>();
        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        contrasteoscuro = new javax.swing.JButton();
        contrastenormal = new javax.swing.JButton();
        aclarar = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        Tintado = new javax.swing.JButton();
        Umbralizador = new javax.swing.JButton();
        Duplicar = new javax.swing.JButton();
        Ecualizacion = new javax.swing.JButton();
        Sepia = new javax.swing.JButton();
        Negativo = new javax.swing.JButton();
        Tinte = new javax.swing.JSlider();
        umbral = new javax.swing.JSlider();
        Random = new javax.swing.JButton();
        jPanel15 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        EspectroColor = new javax.swing.JButton();
        espectro = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jSlider2 = new javax.swing.JSlider();
        jPanel13 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        reducir = new javax.swing.JButton();
        aumentar = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        head = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        nav1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        nav2 = new javax.swing.JPanel();
        lapiz = new javax.swing.JToggleButton();
        linea = new javax.swing.JToggleButton();
        rectangulo = new javax.swing.JToggleButton();
        elipse = new javax.swing.JToggleButton();
        String = new javax.swing.JToggleButton();
        nav3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        degh = new javax.swing.JButton();
        Relleno = new javax.swing.JButton();
        Borde = new javax.swing.JButton();
        Degradado = new javax.swing.JButton();
        degv = new javax.swing.JButton();
        nav4 = new javax.swing.JPanel();
        numeroalisar = new javax.swing.JSpinner();
        relleno = new javax.swing.JToggleButton();
        Alisar = new javax.swing.JToggleButton();
        numtrans = new javax.swing.JSlider();
        jPanel18 = new javax.swing.JPanel();
        botonRecord = new javax.swing.JButton();
        botonplay = new javax.swing.JButton();
        botonstop = new javax.swing.JButton();
        listaReproduccion = new javax.swing.JComboBox<>();
        jPanel17 = new javax.swing.JPanel();
        jPanel19 = new javax.swing.JPanel();
        jPanel20 = new javax.swing.JPanel();
        Subir = new javax.swing.JButton();
        Bajar = new javax.swing.JButton();
        Eliminar = new javax.swing.JButton();
        jPanel22 = new javax.swing.JPanel();
        jPanel23 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        X = new javax.swing.JSpinner();
        jPanel24 = new javax.swing.JPanel();
        mod = new javax.swing.JButton();
        jPanel25 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        Y = new javax.swing.JSpinner();
        jScrollPane2 = new javax.swing.JScrollPane();
        li = new javax.swing.JList<>();
        Escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        File = new javax.swing.JMenu();
        FileNuevo = new javax.swing.JMenuItem();
        FileAbrir = new javax.swing.JMenuItem();
        FileGuardar = new javax.swing.JMenuItem();
        Edicion = new javax.swing.JMenu();
        EdicionVerbarra = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem2 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem3 = new javax.swing.JCheckBoxMenuItem();
        jMenu1 = new javax.swing.JMenu();
        Acercade = new javax.swing.JMenuItem();

        jButton4.setText("jButton4");

        list.setText("jMenu3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pie.setPreferredSize(new java.awt.Dimension(2409, 100));
        pie.setLayout(new java.awt.BorderLayout());

        estado.setText("Paint");
        pie.add(estado, java.awt.BorderLayout.PAGE_END);

        jPanel1.setMinimumSize(new java.awt.Dimension(869, 50));
        jPanel1.setPreferredSize(new java.awt.Dimension(2409, 80));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator3.setMaximumSize(new java.awt.Dimension(10, 10));
        jSeparator3.setPreferredSize(new java.awt.Dimension(10, 10));
        jSeparator3.setRequestFocusEnabled(false);
        jPanel1.add(jSeparator3);

        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.LINE_AXIS));

        jPanel4.setPreferredSize(new java.awt.Dimension(100, 32));
        jPanel4.setLayout(new java.awt.GridLayout(0, 1));

        jLabel1.setText("Brillo");
        jPanel4.add(jLabel1);

        jSlider1.setMinimum(-100);
        jSlider1.setToolTipText("Brillo");
        jSlider1.setValue(0);
        jSlider1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider1StateChanged(evt);
            }
        });
        jSlider1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jSlider1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jSlider1FocusLost(evt);
            }
        });
        jPanel4.add(jSlider1);

        jPanel2.add(jPanel4);

        jPanel5.setPreferredSize(new java.awt.Dimension(60, 48));
        jPanel5.setLayout(new java.awt.GridLayout(0, 1));

        jLabel2.setText("Filtro");
        jPanel5.add(jLabel2);

        Filtro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "media", "binomial", "enfoque", "relieve", "laplaciano" }));
        Filtro.setSelectedItem("Seleccione");
        Filtro.setToolTipText("Varios Filtros");
        Filtro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FiltroActionPerformed(evt);
            }
        });
        jPanel5.add(Filtro);

        jPanel2.add(jPanel5);

        jPanel6.setPreferredSize(new java.awt.Dimension(100, 52));
        jPanel6.setLayout(new java.awt.GridLayout(0, 1));

        jLabel3.setText("Contraste");
        jPanel6.add(jLabel3);

        jPanel9.setLayout(new java.awt.GridLayout(0, 3));

        contrasteoscuro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/oscurecer.png"))); // NOI18N
        contrasteoscuro.setToolTipText("Oscurecer");
        contrasteoscuro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contrasteoscuroActionPerformed(evt);
            }
        });
        jPanel9.add(contrasteoscuro);

        contrastenormal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/contraste.png"))); // NOI18N
        contrastenormal.setToolTipText("Contraste");
        contrastenormal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contrastenormalActionPerformed(evt);
            }
        });
        jPanel9.add(contrastenormal);

        aclarar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iluminar.png"))); // NOI18N
        aclarar.setToolTipText("Iluminado");
        aclarar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aclararActionPerformed(evt);
            }
        });
        jPanel9.add(aclarar);

        jPanel6.add(jPanel9);

        jPanel2.add(jPanel6);

        jPanel10.setMaximumSize(new java.awt.Dimension(900, 70));
        jPanel10.setMinimumSize(new java.awt.Dimension(900, 70));
        jPanel10.setPreferredSize(new java.awt.Dimension(900, 70));
        jPanel10.setLayout(new java.awt.GridLayout(2, 3));

        jButton9.setText("MiFuncion (sqrt(log10(x))");
        jButton9.setToolTipText("Mi funcion");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel10.add(jButton9);

        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/sinusoidal.png"))); // NOI18N
        jButton10.setToolTipText("Funcion seno");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel10.add(jButton10);

        Tintado.setText("Tintado(Relleno)");
        Tintado.setToolTipText("Aplicar Tintado ( Color del Relleno)");
        Tintado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TintadoActionPerformed(evt);
            }
        });
        jPanel10.add(Tintado);

        Umbralizador.setText("Umbralizacion");
        Umbralizador.setToolTipText("Aplicar Filtro umbralizacion");
        Umbralizador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UmbralizadorActionPerformed(evt);
            }
        });
        jPanel10.add(Umbralizador);

        Duplicar.setText("Duplicar");
        Duplicar.setToolTipText("Duplicar imagen seleccionada");
        Duplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DuplicarActionPerformed(evt);
            }
        });
        jPanel10.add(Duplicar);

        Ecualizacion.setText("Ecualizacion");
        Ecualizacion.setToolTipText("Ecualizacion de la imagen");
        Ecualizacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EcualizacionActionPerformed(evt);
            }
        });
        jPanel10.add(Ecualizacion);

        Sepia.setText("Sepia");
        Sepia.setToolTipText("Aplicar fitro sepia");
        Sepia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SepiaActionPerformed(evt);
            }
        });
        jPanel10.add(Sepia);

        Negativo.setText("Negativo");
        Negativo.setToolTipText("Aplicar Filtro negativo");
        Negativo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NegativoActionPerformed(evt);
            }
        });
        jPanel10.add(Negativo);
        jPanel10.add(Tinte);

        umbral.setMaximum(255);
        umbral.setValue(125);
        jPanel10.add(umbral);

        Random.setText("RandomFiltro");
        Random.setToolTipText("Aplicar filtro Random");
        Random.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RandomActionPerformed(evt);
            }
        });
        jPanel10.add(Random);

        jPanel2.add(jPanel10);

        jPanel15.setLayout(new java.awt.GridLayout(0, 1));

        jLabel6.setText("Color");
        jPanel15.add(jLabel6);

        jPanel16.setLayout(new java.awt.GridLayout(1, 0));

        EspectroColor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bandas.png"))); // NOI18N
        EspectroColor.setToolTipText("Extraer bandas");
        EspectroColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EspectroColorActionPerformed(evt);
            }
        });
        jPanel16.add(EspectroColor);

        espectro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "RGB", "YCC", "GREY" }));
        espectro.setToolTipText("Espectro de color");
        espectro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                espectroActionPerformed(evt);
            }
        });
        jPanel16.add(espectro);

        jPanel15.add(jPanel16);

        jPanel2.add(jPanel15);

        jPanel3.setLayout(new java.awt.GridLayout(0, 1));

        jLabel4.setText("Rotacion");
        jPanel3.add(jLabel4);

        jPanel12.setLayout(new java.awt.GridLayout(1, 0));

        jSlider2.setMaximum(360);
        jSlider2.setToolTipText("Rotacion");
        jSlider2.setPreferredSize(new java.awt.Dimension(100, 16));
        jSlider2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider2StateChanged(evt);
            }
        });
        jSlider2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jSlider2FocusLost(evt);
            }
        });
        jSlider2.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jSlider2PropertyChange(evt);
            }
        });
        jPanel12.add(jSlider2);

        jPanel3.add(jPanel12);

        jPanel2.add(jPanel3);

        jPanel13.setLayout(new java.awt.GridLayout(0, 1));

        jLabel5.setText("Escala");
        jPanel13.add(jLabel5);

        jPanel14.setLayout(new java.awt.GridLayout(1, 0));

        reducir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/disminuir.png"))); // NOI18N
        reducir.setToolTipText("Disminuir Escala");
        reducir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reducirActionPerformed(evt);
            }
        });
        jPanel14.add(reducir);

        aumentar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/aumentar.png"))); // NOI18N
        aumentar.setToolTipText("Aumentar Escala");
        aumentar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aumentarActionPerformed(evt);
            }
        });
        jPanel14.add(aumentar);

        jPanel13.add(jPanel14);

        jPanel2.add(jPanel13);

        jPanel1.add(jPanel2);

        pie.add(jPanel1, java.awt.BorderLayout.PAGE_START);
        pie.add(jSeparator2, java.awt.BorderLayout.CENTER);

        getContentPane().add(pie, java.awt.BorderLayout.PAGE_END);

        head.setLayout(new java.awt.GridLayout(1, 0));

        jPanel8.setLayout(new java.awt.GridLayout(1, 0));

        nav1.setLayout(new java.awt.GridLayout(1, 0));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/NuevoBoceto.GIF"))); // NOI18N
        jButton1.setToolTipText("Nuevo Lienzo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        nav1.add(jButton1);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/abrir.png"))); // NOI18N
        jButton2.setToolTipText("Abrir Archivo");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FileAbrirActionPerformed(evt);
            }
        });
        nav1.add(jButton2);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Guardar.gif"))); // NOI18N
        jButton3.setToolTipText("Guardar Archivo");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FileGuardarActionPerformed(evt);
            }
        });
        nav1.add(jButton3);

        jPanel8.add(nav1);

        nav2.setLayout(new java.awt.GridLayout(1, 0));

        lapiz.setName("Lapiz");
        menu.add(lapiz);
        lapiz.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Lapiz.gif"))); // NOI18N
        lapiz.setToolTipText("Punto");
        lapiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                herramienta(evt);
            }
        });
        nav2.add(lapiz);

        linea.setName("Linea");
        menu.add(linea);
        linea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Linea.gif"))); // NOI18N
        linea.setToolTipText("Linea");
        linea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                herramienta(evt);
            }
        });
        nav2.add(linea);

        rectangulo.setName("Rectangulo");
        menu.add(rectangulo);
        rectangulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Rectangulo.gif"))); // NOI18N
        rectangulo.setToolTipText("Rectangulo");
        rectangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                herramienta(evt);
            }
        });
        nav2.add(rectangulo);

        elipse.setName("Elipse");
        menu.add(elipse);
        elipse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Ovalo.gif"))); // NOI18N
        elipse.setToolTipText("Elipse");
        elipse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                herramienta(evt);
            }
        });
        nav2.add(elipse);

        String.setName("string");
        menu.add(String);
        String.setText("S");
        String.setToolTipText("String");
        String.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                herramienta(evt);
            }
        });
        nav2.add(String);

        jPanel8.add(nav2);

        nav3.setLayout(new java.awt.GridLayout(0, 4));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Relleno");
        nav3.add(jLabel7);

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Borde");
        nav3.add(jLabel8);

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Degradado");
        nav3.add(jLabel11);

        degh.setText("Horizontal");
        degh.setToolTipText("Degradado horizontal");
        degh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deghActionPerformed(evt);
            }
        });
        nav3.add(degh);

        Relleno.setToolTipText("Color Relleno");
        Relleno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RellenoActionPerformed(evt);
            }
        });
        nav3.add(Relleno);

        Borde.setToolTipText("Color Borde");
        Borde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BordeActionPerformed(evt);
            }
        });
        nav3.add(Borde);

        Degradado.setToolTipText("Color Degradado");
        Degradado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DegradadoActionPerformed(evt);
            }
        });
        nav3.add(Degradado);

        degv.setText("Vertical");
        degv.setToolTipText("degradado vertical");
        degv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                degvActionPerformed(evt);
            }
        });
        nav3.add(degv);

        jPanel8.add(nav3);

        nav4.setLayout(new java.awt.GridLayout(1, 0));

        numeroalisar.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        numeroalisar.setToolTipText("Grosor");
        numeroalisar.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                numeroalisarStateChanged(evt);
            }
        });
        nav4.add(numeroalisar);

        relleno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/rellenar.png"))); // NOI18N
        relleno.setToolTipText("Relleno");
        relleno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rellenoActionPerformed(evt);
            }
        });
        nav4.add(relleno);

        Alisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/alisar.png"))); // NOI18N
        Alisar.setToolTipText("Alisar");
        Alisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlisarActionPerformed(evt);
            }
        });
        nav4.add(Alisar);

        numtrans.setMaximum(255);
        numtrans.setToolTipText("Transparencia");
        numtrans.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                numtransStateChanged(evt);
            }
        });
        nav4.add(numtrans);

        jPanel8.add(nav4);

        jPanel18.setLayout(new java.awt.GridBagLayout());

        botonRecord.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/record24x24.png"))); // NOI18N
        botonRecord.setToolTipText("Grabar");
        botonRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRecordActionPerformed(evt);
            }
        });
        jPanel18.add(botonRecord, new java.awt.GridBagConstraints());

        botonplay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/play24x24.png"))); // NOI18N
        botonplay.setToolTipText("Play");
        botonplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonplayActionPerformed(evt);
            }
        });
        jPanel18.add(botonplay, new java.awt.GridBagConstraints());

        botonstop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/stop24x24.png"))); // NOI18N
        botonstop.setToolTipText("Parar");
        botonstop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonstopActionPerformed(evt);
            }
        });
        jPanel18.add(botonstop, new java.awt.GridBagConstraints());

        listaReproduccion.setToolTipText("Lista de reproduccion");
        listaReproduccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaReproduccionActionPerformed(evt);
            }
        });
        jPanel18.add(listaReproduccion, new java.awt.GridBagConstraints());

        jPanel8.add(jPanel18);

        head.add(jPanel8);

        getContentPane().add(head, java.awt.BorderLayout.PAGE_START);

        jPanel17.setMaximumSize(new java.awt.Dimension(542, 763));
        jPanel17.setMinimumSize(new java.awt.Dimension(542, 763));
        jPanel17.setLayout(new java.awt.BorderLayout());

        jPanel19.setLayout(new java.awt.BorderLayout());

        jPanel20.setLayout(new java.awt.GridBagLayout());

        Subir.setText("Subir");
        Subir.setToolTipText("Aumentar propiedad de figura");
        Subir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubirActionPerformed(evt);
            }
        });
        jPanel20.add(Subir, new java.awt.GridBagConstraints());

        Bajar.setText("Bajar");
        Bajar.setToolTipText("Disminuir propiedad de figura");
        Bajar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BajarActionPerformed(evt);
            }
        });
        jPanel20.add(Bajar, new java.awt.GridBagConstraints());

        Eliminar.setText("Eliminar");
        Eliminar.setToolTipText("Eliminar Figura");
        Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarActionPerformed(evt);
            }
        });
        jPanel20.add(Eliminar, new java.awt.GridBagConstraints());

        jPanel19.add(jPanel20, java.awt.BorderLayout.PAGE_START);

        jPanel17.add(jPanel19, java.awt.BorderLayout.PAGE_START);

        jPanel22.setLayout(new java.awt.GridBagLayout());

        jPanel23.setLayout(new java.awt.GridLayout(0, 1));

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Coordenada X");
        jPanel23.add(jLabel9);

        X.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        X.setPreferredSize(new java.awt.Dimension(80, 30));
        X.setRequestFocusEnabled(false);
        X.setValue(1);
        X.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                XValor(evt);
            }
        });
        jPanel23.add(X);

        jPanel22.add(jPanel23, new java.awt.GridBagConstraints());

        jPanel24.setLayout(new java.awt.BorderLayout());

        mod.setText("Aceptar");
        mod.setToolTipText("Mover Figura");
        mod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modActionPerformed(evt);
            }
        });
        jPanel24.add(mod, java.awt.BorderLayout.CENTER);

        jPanel22.add(jPanel24, new java.awt.GridBagConstraints());

        jPanel25.setLayout(new java.awt.GridLayout(0, 1));

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Coordenada Y");
        jPanel25.add(jLabel10);

        Y.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        Y.setPreferredSize(new java.awt.Dimension(80, 30));
        Y.setValue(1);
        Y.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                YValor(evt);
            }
        });
        jPanel25.add(Y);

        jPanel22.add(jPanel25, new java.awt.GridBagConstraints());

        jPanel17.add(jPanel22, java.awt.BorderLayout.PAGE_END);

        jScrollPane2.setMinimumSize(new java.awt.Dimension(259, 131));

        li.setModel(list_model);
        li.setMaximumSize(new java.awt.Dimension(40, 180));
        li.setMinimumSize(new java.awt.Dimension(40, 180));
        li.setPreferredSize(new java.awt.Dimension(40, 180));
        li.setValueIsAdjusting(true);
        li.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                liValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(li);

        jPanel17.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel17, java.awt.BorderLayout.LINE_END);

        Escritorio.setMaximumSize(new java.awt.Dimension(1841, 732));
        Escritorio.setMinimumSize(new java.awt.Dimension(1841, 732));
        Escritorio.setName(""); // NOI18N

        javax.swing.GroupLayout EscritorioLayout = new javax.swing.GroupLayout(Escritorio);
        Escritorio.setLayout(EscritorioLayout);
        EscritorioLayout.setHorizontalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2124, Short.MAX_VALUE)
        );
        EscritorioLayout.setVerticalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 771, Short.MAX_VALUE)
        );

        getContentPane().add(Escritorio, java.awt.BorderLayout.CENTER);

        File.setText("Archivo");
        File.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                FileMouseEntered(evt);
            }
        });
        File.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FileActionPerformed(evt);
            }
        });

        FileNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/NuevoBoceto.GIF"))); // NOI18N
        FileNuevo.setText("Nuevo");
        menu.add(FileNuevo);
        FileNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FileNuevoActionPerformed(evt);
            }
        });
        File.add(FileNuevo);

        FileAbrir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/abrir.png"))); // NOI18N
        FileAbrir.setText("Abrir");
        FileAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FileAbrirActionPerformed(evt);
            }
        });
        File.add(FileAbrir);

        FileGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Guardar.gif"))); // NOI18N
        FileGuardar.setText("Guardar");
        FileGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FileGuardarActionPerformed(evt);
            }
        });
        File.add(FileGuardar);

        jMenuBar1.add(File);

        Edicion.setText("Edición");

        EdicionVerbarra.setSelected(true);
        EdicionVerbarra.setText("Ver barra de estado");
        EdicionVerbarra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EdicionVerbarraActionPerformed(evt);
            }
        });
        Edicion.add(EdicionVerbarra);

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("Ver barra de formas");
        jCheckBoxMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItem1ActionPerformed(evt);
            }
        });
        Edicion.add(jCheckBoxMenuItem1);

        jCheckBoxMenuItem2.setSelected(true);
        jCheckBoxMenuItem2.setText("Ver barra de atributos");
        jCheckBoxMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItem2ActionPerformed(evt);
            }
        });
        Edicion.add(jCheckBoxMenuItem2);

        jCheckBoxMenuItem3.setSelected(true);
        jCheckBoxMenuItem3.setText("Ver tratamiento de imagen");
        jCheckBoxMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItem3ActionPerformed(evt);
            }
        });
        Edicion.add(jCheckBoxMenuItem3);

        jMenuBar1.add(Edicion);

        jMenu1.setText("Ayuda");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        Acercade.setText("Acerca de");
        Acercade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AcercadeActionPerformed(evt);
            }
        });
        jMenu1.add(Acercade);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FileMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FileMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_FileMouseEntered
    /**
    *
    * Guarda el archivo
    * 
    */
    private void FileGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FileGuardarActionPerformed
        // TODO add your handling code here:
        if(listaReproduccion.getSelectedItem() ==null){
            VentanaInterna vi=(VentanaInterna)Escritorio.getSelectedFrame();   
            if (vi != null) {     
                JFileChooser dlg = new JFileChooser();
            
            int resp = dlg.showSaveDialog(this);     
            if (resp == JFileChooser.APPROVE_OPTION) {     
                try {       
                    BufferedImage img = vi.getLienzoImagen().getImagen(true);      
                    if (img != null) {        
                        File f = dlg.getSelectedFile();       
                        ImageIO.write(img, "png", f);         
                        vi.setTitle(f.getName());       
                        }    
                    }catch (Exception ex) {       
                        System.err.println("Error al guardar la imagen");     
                    }
                }
            }
        
        }else{
            rec= (File)listaReproduccion.getSelectedItem();
        JFileChooser dlg = new JFileChooser();
       dlg.setSelectedFile(rec);
        int resp = dlg.showSaveDialog(this);
        
        if (resp == JFileChooser.APPROVE_OPTION) {

            File f = new File( dlg.getSelectedFile().getAbsolutePath() ){
                @Override
                public String toString(){
                    return this.getName();
                }
            };
            rec.renameTo(f);

            }
        }
    }//GEN-LAST:event_FileGuardarActionPerformed
    /**
    *
    * Abrir archivo
    * 
    */
    private void FileAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FileAbrirActionPerformed
        // TODO add your handling code here:
        JFileChooser dlg = new JFileChooser();
        int resp = dlg.showOpenDialog(this);
        if( resp == JFileChooser.APPROVE_OPTION) {     
            try{       
                File f = dlg.getSelectedFile();
                
                boolean encontrado = false;
                    int j=0;
                    for(int i=f.toString().length()-1;encontrado;i--){
                        if(f.toString().indexOf(i) == '/'){
                            j=i++;
                            encontrado=true;
                        }
                    }
                    String substring = f.toString().substring(j, f.toString().length());
                    f = new File( substring  ){   
                        @Override   
                        public String toString(){     
                            return this.getName();   
                        } 
                    }; 
                
               
                if(f.toString().contains(".png")||f.toString().contains("jpg")||f.toString().contains("jpeg")){
                    
                    BufferedImage img = ImageIO.read(f);  

                VentanaInterna vi = new VentanaInterna(this,img.getHeight(),img.getWidth()); 
                vi.getLienzoImagen().setImagen(img);      
                vi.setTitle(substring);
                
                this.Escritorio.add(vi);        
                vi.setTitle(f.getName());        
                vi.setVisible(true);     
                actualizarframe();
                vi.actualizardesplazable();
                vi.repaint();
                }
                if(f.toString().contains(".wav") || f.toString().contains(".au") || f.toString().contains(".aif")){
                    
                    listaReproduccion.addItem(f); 

                }
                
            }catch(Exception ex){       
                System.err.println("Error al leer el archivo");     }   }
        
    }//GEN-LAST:event_FileAbrirActionPerformed
    /**
    *
    * Constructor de nuevo lienzo
    * 
    */
    private void FileNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FileNuevoActionPerformed
        // TODO add your handling code here:
         estado.setText("Paint");
        forma = null;
        color = new Color(0,0,0);
        menu.clearSelection();
    }//GEN-LAST:event_FileNuevoActionPerformed
    /**
    *
    * Activar o desactivar la barra de estado
    *
    */
    private void EdicionVerbarraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EdicionVerbarraActionPerformed
        // TODO add your handling code here:
        barraestado = !barraestado;
        estado.setVisible(barraestado);
        
    }//GEN-LAST:event_EdicionVerbarraActionPerformed

 
    /**
    *
    * Actualiza las herramientas dependiendo del frame
    * 
    */
    public void actualizarframe(){
        
        VentanaInterna vi=(VentanaInterna)Escritorio.getSelectedFrame();   

        if (vi != null) {
            jPanel17.setVisible(true);
           
            form = vi.getLienzoImagen().getForma();
            if(form == Formas.PUNTO){
            lapiz.setSelected(true);
             }
            if(form == Formas.LINEA){
            linea.setSelected(true);
             }
            if(form == Formas.RECTANGULO){
            rectangulo.setSelected(true);
             }
            if(form == Formas.ELIPSE){
            elipse.setSelected(true);
             }
            if(form == null){
                vi.getLienzoImagen().setFormas(forma);
            }
            Color col = vi.getLienzoImagen().getBorde();
            Borde.setBackground(col);
            col = vi.getLienzoImagen().getRelleno();
            Relleno.setBackground(col);
            relleno.setSelected(vi.getLienzoImagen().getRellenado());
            numtrans.setValue(vi.getLienzoImagen().getNumtrans());
            Alisar.setSelected(vi.getLienzoImagen().getAlisar());
            numtrans.setValue(vi.getLienzoImagen().getNumtrans());
            numeroalisar.setValue(vi.getLienzoImagen().getGrosor());
            jSlider1.setValue((int)(vi.getLienzoImagen().getBrillo()));
            Filtro.setSelectedItem(vi.getLienzoImagen().getFiltro());
            espectro.setSelectedItem(vi.getLienzoImagen().getEspectro());
            degh.setSelected(vi.getLienzoImagen().getdeghorizontal());
            degv.setSelected(vi.getLienzoImagen().getdegvertical());
            actualizarlista();

        }else{
             jPanel17.setVisible(false);
        }
        
     
    /**
    *
    * Actualiza la lista de objetos Mi Figura
    * 
    */
        
    }
    private void actualizarlista(){
        
        VentanaInterna vi=(VentanaInterna)Escritorio.getSelectedFrame();   
        if (vi != null) {
            list_model = new MiLista();
            
            lista = vi.getLienzoImagen().GetLista();
                lista.forEach((s) -> {
                    
                    list_model.addFigura(s);
                });
            if(list_model.getSize()==0){
                formas =false;
            }else{
                formas = true;
            }
            li.setModel(list_model);
            
        }
    }
    
    
    
    /**
    *
    * Actualiza las herramientas dependiendo de la figura seleccionada
    * @param figura: figura de la que obtenemos los datos
    * 
    */
    private void Actualizarfigura(MiFigura figura){
         VentanaInterna vi=(VentanaInterna)Escritorio.getSelectedFrame();   
        if (vi != null) {
            if(figura !=null){
                Color col = figura.getBorde();
            Borde.setBackground(col);
            vi.getLienzoImagen().setBorde(col);
            numtrans.setValue(figura.getNumtrans());
            vi.getLienzoImagen().setNumtrans(figura.getNumtrans());
            
            Alisar.setSelected(figura.getAlisar());
            vi.getLienzoImagen().setAlisar(figura.getAlisar());
            numeroalisar.setValue(figura.getGrosor());
            vi.getLienzoImagen().setGrosor(figura.getGrosor());
            
            if(figura instanceof MiRectangularShape){
                col = ((MiRectangularShape)figura).getRelleno();
                Relleno.setBackground(col);
                vi.getLienzoImagen().setRelleno(col);
                col = ((MiRectangularShape)figura).getDegradado();
                Degradado.setBackground(col);
                vi.getLienzoImagen().setDegradado(col);
                if(((MiRectangularShape)figura).getRellenado()){
                    relleno.setSelected(true);
                    vi.getLienzoImagen().setRellenado(true);
                    }else{
                    relleno.setSelected(false);
                    vi.getLienzoImagen().setRellenado(false);
                    }
                if(((MiRectangularShape) figura).getVertical()){
                    degv.setSelected(true);
                }else{
                    degv.setSelected(false);
                }
                if(((MiRectangularShape) figura).getHorizontal()){
                    degh.setSelected(true);
                    vi.getLienzoImagen().setdegvertical(true);
                }else{
                    degh.setSelected(false);
                    vi.getLienzoImagen().setdegvertical(false);
                }
            }
           
            }
        }       
    }
    /**
    *
    * Envia una señal al lienzo con la forma que queremos dibujar
    * 
    */
    private void herramienta(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_herramienta
        // TODO add your handling code here:
        javax.swing.JToggleButton boton;
        boton = (javax.swing.JToggleButton) evt.getSource();
        switch (boton.getName()){
            case "Lapiz":
                forma=Formas.PUNTO;
                break;
            case "Linea":
                forma = Formas.LINEA;
                break;
            case "Rectangulo":
                forma = Formas.RECTANGULO;
                break;
            case "Elipse":
                forma = Formas.ELIPSE;
                break;
            case "string":
                 new SelString(this,false).setVisible(true);
                forma = Formas.STRING;
                break;
            
        }      
        estado.setText(forma.toString());
        VentanaInterna vi;  
        vi = (VentanaInterna)Escritorio.getSelectedFrame();
        if(vi != null){
            vi.getLienzoImagen().setFormas(forma);
            if(li.getSelectedValue()!= null){
                actualizarlista();
            }
            
        }
    }//GEN-LAST:event_herramienta

    private void FileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FileActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_FileActionPerformed
    /**
    *
    * Activa y desactiva la barra de herramientas
    * 
    */
    private void jCheckBoxMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItem1ActionPerformed
        // TODO add your handling code here:
        barraformas = !barraformas;
        nav2.setVisible(barraformas);
        
    }//GEN-LAST:event_jCheckBoxMenuItem1ActionPerformed
    /**
    *
    * Crea un nuevo lienzo
    * @param altura: selecciona la altura del lienzo
    * @param anchura: selecciona la anchura del lienzo
    * 
    */
    public void nuevoLienzo(int altura,int anchura){
        if(anchura != 0 && altura != 0){
            VentanaInterna vi = new VentanaInterna(this,anchura,altura);
            Escritorio.add(vi);
            vi.setVisible(true);
            actualizarframe();
            altura =0;
            anchura=0;
            }
    }
    /**
    *
    * Abre el cuadro de seleccion de tamaño del lienzo
    * 
    */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new SelLienzo(this).setVisible(true);
         
         
    }//GEN-LAST:event_jButton1ActionPerformed
    /**
    *
    * Activa el relleno
    * 
    */
    private void rellenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rellenoActionPerformed
        // TODO add your handling code here:
        VentanaInterna vi;  
        vi = (VentanaInterna)Escritorio.getSelectedFrame();
        if(vi != null){
        vi.getLienzoImagen().setRellenado(!vi.getLienzoImagen().getRellenado());
        if(li.getSelectedValue() != null){
        if(li.getSelectedValue() instanceof MiRectangularShape){
            ((MiRectangularShape)li.getSelectedValue()).setRellenado(!((MiRectangularShape)li.getSelectedValue()).getRellenado());
        }

        vi.getLienzoImagen().repaint();
        }
        }
        
    }//GEN-LAST:event_rellenoActionPerformed
    /**
    *
    * Activa el alisado
    * 
    */
    private void AlisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlisarActionPerformed
        // TODO add your handling code here:
        VentanaInterna vi;  
        vi = (VentanaInterna)Escritorio.getSelectedFrame();
        if(vi != null){
            vi.getLienzoImagen().setAlisar(!vi.getLienzoImagen().getAlisar());
        if(li.getSelectedValue() != null){
            li.getSelectedValue().setAlisar(!li.getSelectedValue().getAlisar());
            vi.getLienzoImagen().repaint();
        }
        
        }
    }//GEN-LAST:event_AlisarActionPerformed
    /**
    *
    * Modifica el numero del alisado
    * 
    */
    private void numeroalisarStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_numeroalisarStateChanged
        // TODO add your handling code here:
       VentanaInterna vi;  
        vi = (VentanaInterna)Escritorio.getSelectedFrame();
        if(vi != null){
            vi.getLienzoImagen().setGrosor(Integer.parseInt(numeroalisar.getValue().toString()));
        if(li.getSelectedValue() != null){
            li.getSelectedValue().setGrosor(Integer.parseInt(numeroalisar.getValue().toString()));
            vi.getLienzoImagen().repaint();
            }
        }
    }//GEN-LAST:event_numeroalisarStateChanged
    /**
    *
    * activa y desactiva la barra de los atributos
    * 
    */
    private void jCheckBoxMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItem2ActionPerformed
        // TODO add your handling code here:
        barraatributos = !barraatributos;
        nav3.setVisible(barraatributos);
        nav4.setVisible(barraatributos);
    }//GEN-LAST:event_jCheckBoxMenuItem2ActionPerformed
    /**
    *
    * Selecciona un filtro para la immagen
    * 
    */
    private void FiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FiltroActionPerformed
        // TODO add your handling code here:
        
        VentanaInterna vi = (VentanaInterna) this.Escritorio.getSelectedFrame();
        if (vi != null)
        {   if(Filtro.getSelectedItem().toString() != "Seleccione"){
            imgSource = vi.getLienzoImagen().getImagen(false);
            if (this.imgSource != null)
                try
                {
                    Kernel k = null;
                    vi.getLienzoImagen().setFiltro(Filtro.getSelectedItem().toString());
                    
                    switch (Filtro.getSelectedItem().toString())
                    {
                        case "media": 
                            k = KernelProducer.createKernel(KernelProducer.TYPE_MEDIA_3x3);
                            break;
                        case "binomial":
                            k = KernelProducer.createKernel(KernelProducer.TYPE_BINOMIAL_3x3);
                            break;
                        case "enfoque":
                            k = KernelProducer.createKernel(KernelProducer.TYPE_ENFOQUE_3x3);
                            break;
                        case "relieve":
                            k = KernelProducer.createKernel(KernelProducer.TYPE_RELIEVE_3x3);
                            break;
                        case "laplaciano":
                            k = KernelProducer.createKernel(KernelProducer.TYPE_LAPLACIANA_3x3);
                            break;
                        
                    }
                    if (k != null)
                    {
                        ConvolveOp cop = new ConvolveOp(k,ConvolveOp.EDGE_NO_OP, null);
                        BufferedImage imgSource = cop.filter(this.imgSource, null);
                        vi.getLienzoImagen().setImagen(imgSource);
                        vi.getLienzoImagen().repaint();
                    }

                } catch (Exception e)
                {
                    System.err.println("Error");
                }
            }
        }


       
        
    }//GEN-LAST:event_FiltroActionPerformed

    private void jSlider1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jSlider1FocusGained
        // TODO add your handling code here:
          VentanaInterna vi =(VentanaInterna)(Escritorio.getSelectedFrame());
          if(vi != null){
              imgSource = vi.getLienzoImagen().getImagen(false);
          }
    }//GEN-LAST:event_jSlider1FocusGained

    private void jSlider1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jSlider1FocusLost
        // TODO add your handling code here:
        imgSource =null;
        
    }//GEN-LAST:event_jSlider1FocusLost
    /**
    *
    * Selecciona el brillo de la imagen
    * 
    */
    private void jSlider1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider1StateChanged
        // TODO add your handling code here:
        VentanaInterna vi = (VentanaInterna)(Escritorio.getSelectedFrame());
        float value = this.jSlider1.getValue();
        vi.getLienzoImagen().setBrillo(value);
        if (vi != null && imgSource != null)
            try
            {
                RescaleOp rop;
                if (this.imgSource.getColorModel().hasAlpha())
                {
                    float[] scales = new float[]{1.0f, 1.0f, 1.0f, 1.0f};
                    float[] offsets = new float[]{value, value, value, 0.0f};
                    rop = new RescaleOp(scales, offsets, null);
                } else{
                    rop = new RescaleOp(1.0f, value, null);
                }
                BufferedImage imgdest = rop.filter(this.imgSource, null);
                vi.getLienzoImagen().setImagen(imgdest);
                vi.getLienzoImagen().repaint();
                
            } catch (Exception e)
            {
                System.err.println("Error");
            }
    }//GEN-LAST:event_jSlider1StateChanged
    /**
    *
    * Selecciona un contraste
    * 
    */
    private void contrasteoscuroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contrasteoscuroActionPerformed
        // TODO add your handling code here:
        VentanaInterna vi = (VentanaInterna) (Escritorio.getSelectedFrame());   
        if (vi != null) {     
            BufferedImage imgSource = vi.getLienzoImagen().getImagen(false);
             if(imgSource!=null){             
                try{              
                    int type = LookupTableProducer.TYPE_GAMMA_CORRECTION;
            
                    LookupTable l = LookupTableProducer.createLookupTable(type);    
                    l = LookupTableProducer.gammaCorrection(LookupTableProducer.DEFAULT_A_GAMMA, LookupTableProducer.TYPE_GAMMA_CORRECTION);
                    LookupOp lop = new LookupOp(l, null);                 
                    lop.filter( imgSource , imgSource);         
                    vi.repaint();       
            } catch(Exception e){           
                System.err.println(e.getLocalizedMessage());       
            }           
            }   
        }
    }//GEN-LAST:event_contrasteoscuroActionPerformed
    /**
    *
    * Selecciona un contraste
    * 
    */
    private void contrastenormalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contrastenormalActionPerformed
        // TODO add your handling code here:
        VentanaInterna vi = (VentanaInterna) (Escritorio.getSelectedFrame());   
        if (vi != null) {     
            BufferedImage imgSource = vi.getLienzoImagen().getImagen(false);
             if(imgSource!=null){             
                try{              
                int type = LookupTableProducer.TYPE_SFUNCION;
                LookupTable l = LookupTableProducer.createLookupTable(type);
                l = LookupTableProducer.gammaCorrection(LookupTableProducer.TYPE_GAMMA_CORRECTION, LookupTableProducer.DEFAULT_GAMMA);
                LookupOp lop = new LookupOp(l, null);                 
                lop.filter( imgSource , imgSource);         
                vi.repaint();       
                } catch(Exception e){           
                    System.err.println(e.getLocalizedMessage());       
            }           
            }      
        }
    }//GEN-LAST:event_contrastenormalActionPerformed
    /**
    *
    * Selecciona un contraste
    * 
    */
    private void aclararActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aclararActionPerformed
        // TODO add your handling code here:
        VentanaInterna vi = (VentanaInterna) (Escritorio.getSelectedFrame());   
        if (vi != null) {     
            BufferedImage imgSource = vi.getLienzoImagen().getImagen(false);
             if(imgSource!=null){             
                try{              
                    int type = LookupTableProducer.TYPE_LOGARITHM;
                    LookupTable l = LookupTableProducer.logarithmFuction();
                    LookupOp lop = new LookupOp(l, null);                 
                    lop.filter( imgSource , imgSource);         
                    vi.repaint();       
                } catch(Exception e){           
                System.err.println(e.getLocalizedMessage());       
                }           
            }   
        }
    }//GEN-LAST:event_aclararActionPerformed
    /**
    *
    * Selecciona un filtro
    * 
    */
    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        VentanaInterna vi = (VentanaInterna) Escritorio.getSelectedFrame();
        imgSource = vi.getLienzoImagen().getImagen(false);
        
        if (vi != null){
            try
            {
                LookupTable lt = seno(180);
                LookupOp lop = new LookupOp(lt, null);
                lop.filter(imgSource, imgSource);
                vi.repaint();
            } catch (Exception e)
            {
                System.err.println("Error");
            }
        }
    }//GEN-LAST:event_jButton10ActionPerformed
     /**
    *
    * Abre el cuadro de dialogo y selecciona el string 
    *  a poner de la forma MiString
    * 
    */
    public void setString(String string){
        
        VentanaInterna vi = (VentanaInterna) Escritorio.getSelectedFrame();
        if(vi != null){
            vi.getLienzoImagen().setString(string);
        }
    }

    private void jSlider2PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jSlider2PropertyChange
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jSlider2PropertyChange
    /**
    *
    * Rota la imagen
    * 
    */
    private void jSlider2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider2StateChanged
        // TODO add your handling code here:
            
            VentanaInterna vi = (VentanaInterna) (Escritorio.getSelectedFrame()); 
        if (vi != null) {
            if(imgSource == null){
                imgSource = vi.getLienzoImagen().getImagen(true);
            }
            if(formas){
                imgSource = vi.getLienzoImagen().getImagen(true);
                actualizarlista();
                formas=false;
            }
            try{

                BufferedImage Dest = new BufferedImage(imgSource.getHeight(), imgSource.getWidth(), BufferedImage.TYPE_INT_ARGB);
                double r = Math.toRadians(jSlider2.getValue());
                Point p = vi.getLienzoImagen().getPoint();
                AffineTransform at = AffineTransform.getRotateInstance(r,p.x,p.y);
                AffineTransformOp atop = new AffineTransformOp(at,AffineTransformOp.TYPE_BILINEAR);
                Dest = atop.filter(imgSource, null);
                vi.getLienzoImagen().setImagen(Dest);
                vi.repaint();
                
                
            }catch(IllegalArgumentException e){
                System.err.println();
            }  
        }
            
        
    }//GEN-LAST:event_jSlider2StateChanged
    /**
    *
    * Reducir la escala de la imagen
    * 
    */
    private void reducirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reducirActionPerformed
        // TODO add your handling code here:
        VentanaInterna vi = (VentanaInterna) Escritorio.getSelectedFrame();
        if(vi != null){
            escalar(0.75);
            vi.actualizardesplazable();
        }
        
        
        
    }//GEN-LAST:event_reducirActionPerformed
    /**
    *
    * Aumentar la escala de la imagen
    * 
    */
    private void aumentarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aumentarActionPerformed
        // TODO add your handling code here:
        VentanaInterna vi = (VentanaInterna) Escritorio.getSelectedFrame();
        if(vi != null){
            escalar(1.25);
            vi.actualizardesplazable();
        }
    }//GEN-LAST:event_aumentarActionPerformed
    /**
    *
    * Sacar espectro de color
    * 
    */
    private void EspectroColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EspectroColorActionPerformed
        // TODO add your handling code here:
        VentanaInterna vi = (VentanaInterna) Escritorio.getSelectedFrame();
        if(vi != null){
        imgSource = vi.getLienzoImagen().getImagen(true);
        for(int i=0;i<imgSource.getColorModel().getNumColorComponents();i++){
        //Creamos el modelo de color de la nueva imagen basado en un espcio de color GRAY );
            ColorSpace cs = ColorSpace.getInstance(ColorSpace.CS_GRAY); 
            ComponentColorModel cm = new ComponentColorModel(cs, false, false,Transparency.OPAQUE,DataBuffer.TYPE_BYTE);        
            int bandList[] = {i};
            WritableRaster bandRaster = (WritableRaster)imgSource.getRaster().createWritableChild(0,0,imgSource.getWidth(), imgSource.getHeight(), 0, 0, bandList);
            BufferedImage imgBanda = new BufferedImage(cm, bandRaster, false, null);
            VentanaInterna vi2=new VentanaInterna(this,imgSource.getHeight(),imgSource.getWidth());
            vi2.getLienzoImagen().setImagen(imgBanda);
            Escritorio.add(vi2);
            vi2.setTitle(vi2.getTitle()+ i);
            vi2.setVisible(true);
        }
       
        
    }

    /**
    *
    * Consultor de la figura seleccionada
    * 
    */
    }//GEN-LAST:event_EspectroColorActionPerformed
    public int figuraactual(){
        return li.getSelectedIndex();  
    }
    /**
    *
    * Selecciona una figura de la lista de figuras
    * @param i:numero de la figura en la lista
    * 
    */
    public void Seleccionarfigura(int i){
        li.setSelectedIndex(i);
    }
    /**
    *
    * Convierte la imagen segun el espectro de color
    * 
    */
    private void espectroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_espectroActionPerformed
        // TODO add your handling code here:
        VentanaInterna vi = (VentanaInterna) Escritorio.getSelectedFrame();
        if (vi != null)
            
        {
            if(espectro.getSelectedItem().toString()!="Seleccione"){
            imgSource = vi.getLienzoImagen().getImagen(true);
            
            if (this.imgSource != null)
                try
                {
                    BufferedImage imgOut =null;
                    ColorSpace cs=null;
                    ColorConvertOp cop=null;
                    vi.getLienzoImagen().setEspectro(espectro.getSelectedItem().toString());
                    switch (espectro.getSelectedItem().toString())
                    {
                        case "RGB":
                            if(imgSource.getColorModel().getColorSpace().isCS_sRGB()){
                                Escritorio.getSelectedFrame().setTitle("RGB");
                                break;
                            }else{
                                cs = ColorSpace.getInstance(ColorSpace.CS_sRGB);   
                                cop = new ColorConvertOp(cs, null);   
                                imgOut = cop.filter(imgSource, null);
                                Escritorio.getSelectedFrame().setTitle("RGB");
                            }
                            vi.getLienzoImagen().setImagen(imgOut);
                            break;
                        case "YCC":
                            cs = ColorSpace.getInstance(ColorSpace.CS_PYCC);   
                            cop = new ColorConvertOp(cs, null);   
                            imgOut = cop.filter(imgSource, null);
                            Escritorio.getSelectedFrame().setTitle("YCC");
                            vi.getLienzoImagen().setImagen(imgOut);
                            break;
                        case "GREY":
                            cs = ColorSpace.getInstance(ColorSpace.CS_GRAY);   
                            cop = new ColorConvertOp(cs, null);   
                            imgOut = cop.filter(imgSource, null);
                            Escritorio.getSelectedFrame().setTitle("GREY");
                            vi.getLienzoImagen().setImagen(imgOut);
                            break;
                    }
                    
                    vi.repaint();

                } catch (Exception e)
                {
                    System.err.println("Error");
                }
            }
        }
    }//GEN-LAST:event_espectroActionPerformed
    /**
    *
    * Selecciona el color en el lienzo
    * @param tipo: donde va el color(relleno,borde...)
    * @param color: color seleccionado
    * 
    */
    public void selcolor(String tipo,Color color){
        VentanaInterna vi = (VentanaInterna) Escritorio.getSelectedFrame();
         if(vi!=null){
        if (tipo.equals("Relleno")){
            Relleno.setBackground(color);
            vi.getLienzoImagen().setRelleno(color);
            if(li.getSelectedValue() !=null){
                if(li.getSelectedValue() instanceof MiRectangularShape){
                    ((MiRectangularShape)li.getSelectedValue()).setRelleno(color);
                }

                vi.getLienzoImagen().repaint();
            }
        }
        if (tipo.equals("Borde")){
            Borde.setBackground(color);
            vi.getLienzoImagen().setBorde(color);
            if(li.getSelectedValue() !=null){
             li.getSelectedValue().setBorde(color);
             vi.getLienzoImagen().repaint();
            }
        }
        if (tipo.equals("Degradado")){
            Degradado.setBackground(color);
            vi.getLienzoImagen().setDegradado(color);
            if(li.getSelectedValue() !=null){
                if(li.getSelectedValue()  instanceof MiRectangularShape){
                ((MiRectangularShape)li.getSelectedValue()).setDegradado(color);
             vi.getLienzoImagen().repaint();
            }
                
             
            }
            }
         }
    }
    /**
    *
    * Escribe el nombre en el archivo de audio
    * y lo introduce en la lista
    * 
    */
    public void setnamerec(String name){
        File nuevo = new File(name);
        rec.renameTo(nuevo);
        listaReproduccion.addItem(nuevo);
    }
    /**
    *
    * Lanza el cuadro de seleccionar relleno
    * 
    */
    private void RellenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RellenoActionPerformed
        // TODO add your handling code here:
        VentanaInterna vi = (VentanaInterna) Escritorio.getSelectedFrame();
         if(vi!=null){
        new SelCol(this,"Relleno").setVisible(true);
         }
    }//GEN-LAST:event_RellenoActionPerformed
    /**
    *
    * Lanza el cuadro de seleccionar borde
    * 
    */
    private void BordeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BordeActionPerformed
        // TODO add your handling code here:
        VentanaInterna vi = (VentanaInterna) Escritorio.getSelectedFrame();
         if(vi!=null){
        new SelCol(this,"Borde").setVisible(true);
         }
    }//GEN-LAST:event_BordeActionPerformed
    /**
    *
    * Reproduce el audio seleccionado en la lista
    * 
    */
    private void botonplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonplayActionPerformed
        // TODO add your handling code here:
        player = null; 
        File f = (File)listaReproduccion.getSelectedItem(); 
        if(f!=null){   
            player = new SMClipPlayer(f);
            ((SMClipPlayer)player).addLineListener( new ManejadorAudio(botonplay,botonstop));
            if (player != null) {     
                player.play();
                botonstop.setEnabled(true);
                botonRecord.setEnabled(false);
                
            }
        }
    }//GEN-LAST:event_botonplayActionPerformed

    private void listaReproduccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaReproduccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listaReproduccionActionPerformed
    /**
    *
    * Para el audio seleccionado en la lista,
    * o la grabacion de el mismo dando lugar a 
    * seleccionar su nombre.
    * 
    */
    private void botonstopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonstopActionPerformed
        // TODO add your handling code here:
        if (player != null) {     
                player.stop();
                botonplay.setEnabled(true);
                botonstop.setEnabled(false);
                botonRecord.setEnabled(true);
            }
        if (recorder != null){
            recorder.stop();
            recorder = null;
            botonplay.setEnabled(true);
            botonstop.setEnabled(false);
            botonRecord.setEnabled(true);
            new SelString(this,true).setVisible(true);
            
            
        }
    }//GEN-LAST:event_botonstopActionPerformed
    /**
    *
    * Comienza a grabar un audio
    * 
    */
    private void botonRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRecordActionPerformed
        // TODO add your handling code here:
        botonplay.setEnabled(false);
        botonstop.setEnabled(true);
        botonRecord.setEnabled(false);
        recorder = new SMSoundRecorder(rec);
        recorder.record();
        
    }//GEN-LAST:event_botonRecordActionPerformed
    /**
    *
    * Introduce la coordenada X de una figura
    * 
    */
    private void XValor(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_XValor
        // TODO add your handling code here:
        
        cordenadaX = Integer.parseInt(X.getValue().toString());
        

    }//GEN-LAST:event_XValor
    /**
    *
    * Introduce la coordenada Y de una figura
    * 
    */
    private void YValor(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_YValor
        // TODO add your handling code here:
        cordenadaY = Integer.parseInt(Y.getValue().toString());
        

    }//GEN-LAST:event_YValor
    /**
    *
    * Le sube la prioridad a una figura 
    * 
    */
    private void SubirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubirActionPerformed
        // TODO add your handling code here:
        VentanaInterna vi=(VentanaInterna)Escritorio.getSelectedFrame();   
        if (vi != null) {
          int numero = li.getSelectedIndex();
         List<MiFigura> lista = vi.getLienzoImagen().GetLista();
         if(numero < lista.size()-1){
             MiFigura uno = lista.get(numero+1);
             lista.set(numero+1, li.getSelectedValue());
             lista.set(numero, uno);
         }
         vi.getLienzoImagen().setLista(lista);
         actualizarlista();
        }
    }//GEN-LAST:event_SubirActionPerformed
    /**
    *
    * Le baja la prioridad a una figura 
    * 
    */
    private void BajarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BajarActionPerformed
        // TODO add your handling code here:
        VentanaInterna vi=(VentanaInterna)Escritorio.getSelectedFrame();   
        if (vi != null) {
          int numero = li.getSelectedIndex();
         List<MiFigura> lista = vi.getLienzoImagen().GetLista();
         if(numero > 0){
             MiFigura uno = lista.get(numero-1);
             lista.set(numero-1, li.getSelectedValue());
             lista.set(numero, uno);
         }
         vi.getLienzoImagen().setLista(lista);
         actualizarlista();
        }
    }//GEN-LAST:event_BajarActionPerformed
    /**
    *
    * Elimina una figura de la lista
    * 
    */
    private void EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarActionPerformed
        // TODO add your handling code here:
        VentanaInterna vi=(VentanaInterna)Escritorio.getSelectedFrame();   
        if (vi != null) {
          int numero = li.getSelectedIndex();
         lista = vi.getLienzoImagen().GetLista();
             lista.remove(numero);
         vi.getLienzoImagen().setLista(lista);
         actualizarlista();
        }
    }//GEN-LAST:event_EliminarActionPerformed
    /**
    *
    * Actualiza el puntero para mostrar su ubicacion
    * @param x: coordenada de la x
    * @param y: coordenada de la y
    * 
    */
    public void actualizarpuntero(int x,int y){
        cordenadaX = x;
        cordenadaY = y;
        X.setValue(x);
        Y.setValue(y);
    }
    /**
    *
    * Cuando cambiamos la figura seleccionada
    * de la lista
    * 
    */
    private void liValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_liValueChanged
        // TODO add your handling code here:
                Actualizarfigura(li.getSelectedValue());
          VentanaInterna vi=(VentanaInterna)Escritorio.getSelectedFrame();   
        if (vi != null) {
            if(li.getSelectedValue() != null){
               actualizarpuntero((int)li.getSelectedValue().getLocation().getX(),(int)li.getSelectedValue().getLocation().getY());
                vi.getLienzoImagen().setEditar(li.getSelectedIndex());
            }
        }
    }//GEN-LAST:event_liValueChanged
    /**
    *
    * Cambiamos de localizacion la figura seleccionada de
    * la lista
    * 
    */
    private void modActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modActionPerformed
        // TODO add your handling code here:
        VentanaInterna vi=(VentanaInterna)Escritorio.getSelectedFrame();   
        if (vi != null) {
            if(li.getSelectedValue() != null){
          int numero = li.getSelectedIndex();
         lista = vi.getLienzoImagen().GetLista();
         Point2D punto = new Point2D.Double(cordenadaX,cordenadaY);
         lista.get(numero).setLocation(punto);
         vi.getLienzoImagen().setLista(lista);
         vi.getLienzoImagen().repaint();
         this.actualizarlista();
         li.setSelectedIndex(numero);
            }
        }
    }//GEN-LAST:event_modActionPerformed
    /**
    *
    * Aparece el cuadro de dialogo de Acerca de
    * 
    */
    private void AcercadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AcercadeActionPerformed
        // TODO add your handling code here:
        new Acercade(this,true).setVisible(true);
    }//GEN-LAST:event_AcercadeActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1ActionPerformed
    /**
    *
    *  Funcion propia LookuOp: (sqrt(log10(xw))
    * 
    */
    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        VentanaInterna vi = (VentanaInterna) Escritorio.getSelectedFrame();
        imgSource = vi.getLienzoImagen().getImagen(false);
        
        if (vi != null){
            try
            {
                LookupTable lt = mifuncion(180);
                LookupOp lop = new LookupOp(lt, null);
                lop.filter(imgSource, imgSource);
                vi.repaint();
            } catch (Exception e)
            {
                System.err.println("Error");
            }
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jSlider2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jSlider2FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jSlider2FocusLost
    /**
    *
    * Cambia el numero de transparencia
    * 
    */
    private void numtransStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_numtransStateChanged
        // TODO add your handling code here:
        VentanaInterna vi = (VentanaInterna) Escritorio.getSelectedFrame();
        imgSource = vi.getLienzoImagen().getImagen(false);
        
        if (vi != null){
            if(li.getSelectedValue() != null){
                li.getSelectedValue().setNumtrans(numtrans.getValue());
            }else{
            vi.getLienzoImagen().setNumtrans(numtrans.getValue());
            }
            vi.getLienzoImagen().repaint();
        }
    }//GEN-LAST:event_numtransStateChanged
    /**
    *
    * Cambia el  color de degradado
    * 
    */
    private void DegradadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DegradadoActionPerformed
        // TODO add your handling code here:
        VentanaInterna vi = (VentanaInterna) Escritorio.getSelectedFrame();
         if(vi!=null){
        new SelCol(this,"Degradado").setVisible(true);
         }
    }//GEN-LAST:event_DegradadoActionPerformed
    /**
    *
    * Establece el degradado como horizontal
    * 
    */
    private void deghActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deghActionPerformed
        // TODO add your handling code here:
        VentanaInterna vi = (VentanaInterna) Escritorio.getSelectedFrame();
         if(vi!=null){
             if(li.getSelectedValue()!= null){
                 if(li.getSelectedValue() instanceof MiRectangularShape){
                     
                     ((MiRectangularShape)li.getSelectedValue()).setHorizontal(!(((MiRectangularShape)li.getSelectedValue()).getHorizontal()));
                     vi.getLienzoImagen().repaint();
                 }
                 
             }else{
                 vi.getLienzoImagen().setdeghorizontal(!vi.getLienzoImagen().getdeghorizontal());
             }
         }
    }//GEN-LAST:event_deghActionPerformed
    /**
    *
    * Establece el degradado como vertical
    * 
    */
    private void degvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_degvActionPerformed
        // TODO add your handling code here:
        VentanaInterna vi = (VentanaInterna) Escritorio.getSelectedFrame();
         if(vi!=null){
             if(li.getSelectedValue()!= null){
                 if(li.getSelectedValue() instanceof MiRectangularShape){
                     ((MiRectangularShape)li.getSelectedValue()).setVertical(!(((MiRectangularShape)li.getSelectedValue()).getVertical()));
                     vi.getLienzoImagen().repaint();
                 }
                 
             }else{
                 vi.getLienzoImagen().setdegvertical(!vi.getLienzoImagen().getdegvertical());
             }
         }
    }//GEN-LAST:event_degvActionPerformed
    /**
    *
    * Duplicar una imagen
    * 
    */
    private void DuplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DuplicarActionPerformed
        // TODO add your handling code here:
        VentanaInterna vi = (VentanaInterna) Escritorio.getSelectedFrame();
        if(vi!=null){
            BufferedImage copia = new BufferedImage(vi.getLienzoImagen().getImagen(true).getWidth(),vi.getLienzoImagen().getImagen(true).getHeight(),vi.getLienzoImagen().getImagen(true).getType());
            Graphics g = copia.getGraphics();
            g.drawImage(vi.getLienzoImagen().getImagen(true), 0, 0, null);
            VentanaInterna vi2 = new VentanaInterna(this,copia.getHeight(),copia.getWidth());
            vi2.getLienzoImagen().setImagen(copia);
            Escritorio.add(vi2);
            vi2.setTitle("Copia de" + vi.getTitle());
            vi2.setVisible(true);
            actualizarframe();
            vi2.actualizardesplazable();
                vi2.repaint();
            
            }
       
    }//GEN-LAST:event_DuplicarActionPerformed
    /**
    *
    * Tintar una imagen con el color de relleno
    * 
    */
    private void TintadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TintadoActionPerformed
        // TODO add your handling code here:
        VentanaInterna vi = (VentanaInterna) Escritorio.getSelectedFrame();
        if(vi!=null){
            imgSource = vi.getLienzoImagen().getImagen(true);
        TintOp tintado = new TintOp(Relleno.getBackground(),(Tinte.getValue())/100f); 
        tintado.filter(imgSource, imgSource); 
        vi.getLienzoImagen().setImagen(imgSource);
        vi.getLienzoImagen().repaint();
        vi.actualizardesplazable();
        }
    }//GEN-LAST:event_TintadoActionPerformed
    /**
    *
    * Funcion ecualizacion
    * 
    */
    private void EcualizacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EcualizacionActionPerformed
        // TODO add your handling code here:
        VentanaInterna vi = (VentanaInterna) Escritorio.getSelectedFrame();
        if(vi!=null){
            imgSource = vi.getLienzoImagen().getImagen(true);
        EqualizationOp ecualizacion = new EqualizationOp(); 
        ecualizacion.filter(imgSource, imgSource); 
         vi.getLienzoImagen().setImagen(imgSource);
        vi.getLienzoImagen().repaint();
        vi.actualizardesplazable();
        }
    }//GEN-LAST:event_EcualizacionActionPerformed
    /**
    *
    * Filtro Sepia
    * 
    */
    private void SepiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SepiaActionPerformed
        // TODO add your handling code here:
        VentanaInterna vi = (VentanaInterna) Escritorio.getSelectedFrame();
        if(vi!=null){
            imgSource = vi.getLienzoImagen().getImagen(true);
        SepiaOp sepia = new SepiaOp();
        sepia.filter(imgSource, imgSource);
        vi.getLienzoImagen().setImagen(imgSource);
        vi.getLienzoImagen().repaint();
        vi.actualizardesplazable();
        }
    }//GEN-LAST:event_SepiaActionPerformed
    /**
    *
    * Filtro de Umbralizacion
    * 
    */
    private void UmbralizadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UmbralizadorActionPerformed
        // TODO add your handling code here:
        VentanaInterna vi = (VentanaInterna) Escritorio.getSelectedFrame();
        if(vi!=null){
            imgSource = vi.getLienzoImagen().getImagen(true);
        UmbralizacionOp umbralizacion = new UmbralizacionOp(umbral.getValue());
        umbralizacion.filter(imgSource, imgSource);
        vi.getLienzoImagen().setImagen(imgSource);
        vi.getLienzoImagen().repaint();
        vi.actualizardesplazable();
        }
    }//GEN-LAST:event_UmbralizadorActionPerformed
    /**
    *
    * Filtro de la imagen negativo
    * 
    */
    private void NegativoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NegativoActionPerformed
        // TODO add your handling code here:
        VentanaInterna vi = (VentanaInterna) Escritorio.getSelectedFrame();
        if(vi!=null){
            imgSource = vi.getLienzoImagen().getImagen(true);
        NegativoOp negativo = new NegativoOp();
        negativo.filter(imgSource, imgSource);
        vi.getLienzoImagen().setImagen(imgSource);
        vi.getLienzoImagen().repaint();
        vi.actualizardesplazable();
        }
    }//GEN-LAST:event_NegativoActionPerformed
    /**
    *
    * Mi propio Filtro "Random"
    * 
    */
    private void RandomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RandomActionPerformed
        // TODO add your handling code here:
        VentanaInterna vi = (VentanaInterna) Escritorio.getSelectedFrame();
        if(vi!=null){
            imgSource = vi.getLienzoImagen().getImagen(true);
        RandomOp random = new RandomOp();
        random.filter(imgSource, imgSource);
        vi.getLienzoImagen().setImagen(imgSource);
        vi.getLienzoImagen().repaint();
        vi.actualizardesplazable();
        }
    }//GEN-LAST:event_RandomActionPerformed
    /**
    *
    * Activa y desactiva la barra de editar imagenes 
    * 
    */
    private void jCheckBoxMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItem3ActionPerformed
        // TODO add your handling code here:
        barraimagen = !barraimagen;
        jPanel1.setVisible(barraimagen);
        
    }//GEN-LAST:event_jCheckBoxMenuItem3ActionPerformed
    /**
    *
    * Escalar la imagen seleccionada
    * @param indice: valor de la escala
    * 
    */
    private void escalar(double indice){
        VentanaInterna vi = (VentanaInterna) Escritorio.getSelectedFrame();
        imgSource = vi.getLienzoImagen().getImagen(true);
        AffineTransform at = AffineTransform.getScaleInstance(indice, indice);
        AffineTransformOp atop;
        atop = new AffineTransformOp(at,AffineTransformOp.TYPE_BILINEAR); 
        BufferedImage imgdest = atop.filter(imgSource, null);
        vi.getLienzoImagen().setImagen(imgdest);
        vi.repaint();
        vi.actualizardesplazable();
    }
    /**
    *
    * funcion seno
    * 
    */
    private LookupTable seno(double w){
        double K = 255.0; // Cte de normalización
        // Código implementado f(x)=|sin(wx)|
        byte[] lt = new byte[256];
        for (int i = 0; i < 256; ++i)
            lt[i] = (byte)Math.abs(K * Math.sin( w * i ));
        ByteLookupTable slt = new ByteLookupTable(0, lt);
        return slt;
    }
    /**
    *
    * Mi propia funcion raiz cuadrada del logaritmo en base 10 de w*i
    * 
    * 
    */
    private LookupTable mifuncion(double w){
        double K = 255.0; // Cte de normalización
       
        byte[] lt = new byte[256];
        for (int i = 0; i < 256; ++i)
            //La funcion es raiz del log(wx)
            lt[i] = (byte)Math.abs(K * Math.sqrt(Math.log(w * i )));
        ByteLookupTable slt = new ByteLookupTable(0, lt);
        return slt;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Acercade;
    private javax.swing.JToggleButton Alisar;
    private javax.swing.JButton Bajar;
    private javax.swing.JButton Borde;
    private javax.swing.JButton Degradado;
    private javax.swing.JButton Duplicar;
    private javax.swing.JButton Ecualizacion;
    private javax.swing.JMenu Edicion;
    private javax.swing.JCheckBoxMenuItem EdicionVerbarra;
    private javax.swing.JButton Eliminar;
    private javax.swing.JDesktopPane Escritorio;
    private javax.swing.JButton EspectroColor;
    private javax.swing.JMenu File;
    private javax.swing.JMenuItem FileAbrir;
    private javax.swing.JMenuItem FileGuardar;
    private javax.swing.JMenuItem FileNuevo;
    private javax.swing.JComboBox<String> Filtro;
    private javax.swing.JButton Negativo;
    private javax.swing.JButton Random;
    private javax.swing.JButton Relleno;
    private javax.swing.JButton Sepia;
    private javax.swing.JToggleButton String;
    private javax.swing.JButton Subir;
    private javax.swing.JButton Tintado;
    private javax.swing.JSlider Tinte;
    private javax.swing.JButton Umbralizador;
    private javax.swing.JSpinner X;
    private javax.swing.JSpinner Y;
    private javax.swing.JButton aclarar;
    private javax.swing.JButton aumentar;
    private javax.swing.JButton botonRecord;
    private javax.swing.JButton botonplay;
    private javax.swing.JButton botonstop;
    private javax.swing.JButton contrastenormal;
    private javax.swing.JButton contrasteoscuro;
    private javax.swing.JButton degh;
    private javax.swing.JButton degv;
    private javax.swing.JToggleButton elipse;
    private javax.swing.JComboBox<String> espectro;
    private javax.swing.JLabel estado;
    private javax.swing.JPanel head;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton9;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem2;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem3;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JSlider jSlider2;
    private javax.swing.JToggleButton lapiz;
    private javax.swing.JList<MiFigura> li;
    private javax.swing.JToggleButton linea;
    private javax.swing.JMenu list;
    private javax.swing.JComboBox<File> listaReproduccion;
    private javax.swing.ButtonGroup menu;
    private javax.swing.JButton mod;
    private javax.swing.JPanel nav1;
    private javax.swing.JPanel nav2;
    private javax.swing.JPanel nav3;
    private javax.swing.JPanel nav4;
    private javax.swing.JSpinner numeroalisar;
    private javax.swing.JSlider numtrans;
    private javax.swing.JPanel pie;
    private javax.swing.JToggleButton rectangulo;
    private javax.swing.JButton reducir;
    private javax.swing.JToggleButton relleno;
    private javax.swing.JSlider umbral;
    // End of variables declaration//GEN-END:variables
}
